### ISSUE TITLE
Get  familiar with automation across repos

### ISSUE THREAD

**Issue by eladkug** [cyberark/conjur-authn-k8s-client#100]
This is the list of the repos i need to get familiar 

1. Conjur
2. appliance
3. secrets-provider-for-k8s
4. conjur-authn-k8s-client
5. Secretless-broker
6. conjur-cli
7. kubernetes-conjur-deploy
8. summon
9. evoke
10. conjur-ui
11. pet-store-demo
12. kubernetes-conjur-demo

Need to :
1. understand if they lack any testing
2. get familiar with the flow

**Comment by sgnn7** [comment]
Hey @eladkug,
Is this the right repo for the issue you opened? I don't quite see how it relates to cyberark/conjur-authn-k8s-client itself.

**Comment by eladkug** [comment]
closed. opened on the wrong repo, moved to  [AAM](https://app.zenhub.com/workspaces/palmtree-5d99d900491c060001c85cba/issues/conjurinc/aam/153 )
