### ISSUE TITLE
Authenticator client fails to authenticate hosts outside of `apps` branch

### ISSUE THREAD

**Issue by orenbm** [cyberark/conjur-authn-k8s-client#109]
## Summary
We got cases from SEs where the authenticator fails to authenticate hosts outside of the `apps` policy branch. 

## Steps to Reproduce
1. Load a policy with a valid k8s authenticator
1. Load a policy with 2 hosts - one that is in the apps branch and one that is not.
1. Run the authenticator client with `CONJUR_AUTHN_LOGIN=host/conjur/authn-k8s/service-id/apps/ocp_namespace/service_account/ocp_sa`
1. Verify it succeeds.
1. Run the authenticator client with `CONJUR_AUTHN_LOGIN=host/some-policy/ocp_namespace/service_account/ocp_sa`
1. Verify it succeeds.
1. Delete host `conjur/authn-k8s/service-id/apps/ocp_namespace/service_account/ocp_sa` from Conjur
1. Run the authenticator client with `CONJUR_AUTHN_LOGIN=host/some-policy/ocp_namespace/service_account/ocp_sa`

## Expected Results
Authentication succeeds and the application container retrieves a secret.

## Actual Results 
Authentication fails

### Versions
  - DAP: 11.2.1
  - conjur-authn-k8s-client: 0.16.1

**Comment by eladkug** [comment]
This issue was fixed in the past, we got it from SE so we want to verify it before fix/close this issue.

**Comment by orenbm** [comment]
Just to clarify - we didn't test the use case that we remove the host with application identity in the id before authenticating again. 

I am _guessing_ that there is not issue here but we need to verify it.

**Comment by eladkug** [comment]
@jtuttle any news on this?

**Comment by eladkug** [comment]
We have [test](https://github.com/cyberark/secrets-provider-for-k8s/blob/master/deploy/test/test_cases/TEST_ID_13_host_not_in_apps.sh) which verify this scenario under secrets provider.
