### ISSUE TITLE
Run performance test for FIPS-compliant image

### ISSUE THREAD

**Issue by orenbm** [cyberark/conjur-authn-k8s-client#114]
After we make the project FIPS-compliant, we should verify that the performance of the application is not degragated, as described in the [solution design](https://github.com/cyberark/conjur-authn-k8s-client/blob/master/design/fips-compliance.md#performance).

**Comment by izgeri** [comment]
@orenbm it might be good to include info in this issue about what the result was, in case people stumble upon this issue later looking for info.
