### ISSUE TITLE
CONJUR_APPLIANCE_URL - Match Github with DockerHub and docs.cyberark.com

### ISSUE THREAD

**Issue by andresguisado** [cyberark/conjur-authn-k8s-client#128]
$CONJUR_APPLIANCE_URL= https://myurl/api

Is this env var still needed this env var for k8s-authenticator? It is not mentioned in github readme but it is in [dockerhub docs](https://hub.docker.com/r/cyberark/conjur-authn-k8s-client),  [dockerhub2](https://hub.docker.com/r/cyberark/conjur-kubernetes-authenticator)

Also, [Official documentation](CONJUR_APPLIANCE_URL) doesn't mention $CONJUR_APPLIANCE_URL

**Comment by izgeri** [comment]
@andresguisado thanks for filing this issue - I've been able to verify that the `CONJUR_APPLIANCE_URL` is _not_ needed by the k8s authenticator client (this project)

You still _do_ need this to be set, typically, if your app takes the Conjur access token provided by this authenticator client and uses one of Conjur's client libraries to send requests to Conjur. The difference is that the variable needs to be set in the **app container** in that case, and not in the authn-k8s client container.

I hope that helps, and I've updated the DockerHub pages to remove this from the list of required configuration variables in the authenticator client container. Thanks again for flagging this for us!
