### ISSUE TITLE
Secrets Provider (P2) - Research, Read/Update K8s Secrets

### ISSUE THREAD

**Issue by sigalsax** [cyberark/conjur-authn-k8s-client#130]
Phase 2 requires that the Secrets Provider be decoupled from customer application (AKA not sitting with each app in same pod). Additionally, we to handle K8S Secret rotation. 

For this card, we will research how we can perform the K8S Secret update now that the Secrets Provider no longer sits within the App Pod and does not have direct knowledge of which secrets need to be updated.

Solution doc: https://ca-il-confluence.il.cyber-ark.com/pages/viewpage.action?pageId=319161469#/

**Comment by izgeri** [comment]
@sigalsax should this be in cyberark/secrets-provider-for-k8s?

**Comment by sigalsax** [comment]
@izgeri absolutely :x thanks!
