### ISSUE TITLE
Separate debug logs from info

### ISSUE THREAD

**Issue by orenbm** [cyberark/conjur-authn-k8s-client#134]
In cyberark/secrets-provider-for-k8s we have different log levels in which we write messages. This way, log messages that are more for developer debugging can be written only if the user has set the `DEBUG=true` environment variable and the log can be less noisy.

We should add a debug logger and convert any INFO logs that should be logged in debug into DEBUG logs.

DoD:
- [ ] DEBUG log messages are logged only if the `DEBUG=true` env var is presented in the manifest

**Comment by izgeri** [comment]
@orenbm can we also have a method that sets the log level?

Secretless uses this project's code as a library, and `debug` mode is a flag on Secretless. I'd like to propagate the Secretless `debug` mode to this code when I invoke the `authenticator` library methods.
