### ISSUE TITLE
Secrets Provider (P2) - Research keeping pod alive upon process completion

### ISSUE THREAD

**Issue by sigalsax** [cyberark/conjur-authn-k8s-client#138]
A valid solution requires that the Secrets provider be decoupled from customer applications (AKA not sitting with each app in same pod) AND the pod should stay live.

For this card, we will be researching how to keep a pod alive alongside customer applications

Solution doc: https://github.com/cyberark/secrets-provider-for-k8s/pull/122/files

**Comment by izgeri** [comment]
@sigalsax is this meant to be in https://github.com/cyberark/secrets-provider-for-k8s?

**Comment by sigalsax** [comment]
> @sigalsax is this meant to be in https://github.com/cyberark/secrets-provider-for-k8s?

and again! Closing (:
