### ISSUE TITLE
Secrets Provider - JSON schema vs functions

### ISSUE THREAD

**Issue by sigalsax** [cyberark/conjur-authn-k8s-client#142]
DOD
- [ ] Check if we will use JSON schema or HELM functions
- [ ] Talk to @oburstein-hub about what is mainstream and recommendations

**Comment by izgeri** [comment]
@sigalsax just to confirm, this was closed because it was moved to https://github.com/cyberark/secrets-provider-for-k8s?

**Comment by sigalsax** [comment]
yes (:
