### ISSUE TITLE
Support running tests against local cluster and local Openshift deployment

### ISSUE THREAD

**Issue by sigalsax** [cyberark/conjur-authn-k8s-client#143]
This card is a continuation of the previous effort, [deploying a local dev env](https://github.com/cyberark/secrets-provider-for-k8s/commit/a1b09475db7b51fa0aa1ec2364284e4b007997ac). 

The previous effort allowed a dev to deploy a local k8s cluster and does not support deploying a local openshift one yet. Additionally, our tests only run against a remote cluster. This card effort is enable both of these limitations.

DOD
- [ ] run tests against local cluster
- [ ] support OC local deployment
- [ ] Add supporting documentation

**Comment by izgeri** [comment]
what sort of "local k8s cluster" are you running, out of curiosity? are you looking at minishift for local OC?

**Comment by sigalsax** [comment]
I cannot believe I keep spamming you with my card :x 
We started using docker desktopfor k8s deployment, giving us the ability to run a k8s cluster locally. In terms of Openshift, I need to still research that one. It may not be worth also deploying on openshift for dev environments

**Comment by izgeri** [comment]
😁 if it's a zenhub thing, you can change your default repo. maybe you should change yours to secrets provider?

fwiw minishift is different enough from openshift that we had better experiences just deploying on the available dev OC clusters rather than trying to keep things supported between minishift and OC

**Comment by sigalsax** [comment]
> 😁 if it's a zenhub thing, you can change your default repo. maybe you should change yours to secrets provider?
> 
> fwiw minishift is different enough from openshift that we had better experiences just deploying on the available dev OC clusters rather than trying to keep things supported between minishift and OC

this is great! Just changed my default. what a life changing experience

**Comment by izgeri** [comment]
@sigalsax agreed re:minishift. it was disappointing to discover this; maybe it's evolved since?
