### ISSUE TITLE
Align contaners-api with docker-api interface

### ISSUE THREAD

**Issue by moticless** [cyberark/conjur-authn-k8s-client#144]
It is a question of time until podman shall have stable REST API. On that day we should drop our proprietary containers-api library and go back to work with standard docker-api library for ruby. To make this shift back easy, we should strive to align the interface of containers-api with the one of docker-api.

**Comment by izgeri** [comment]
@moticless I wasn't aware this project was doing anything special with `containers-api` vs `docker-api` - can you please share more info on the details of this, maybe with links to relevant code? Thanks.
