### ISSUE TITLE
Constant CSPFK010E Failed to authenticate error on startup

### ISSUE THREAD

**Issue by sigalsax** [cyberark/conjur-authn-k8s-client#146]
## Summary
The following failure log appears every time at the start of Secrets Provider.
```
ERROR: 2020/08/13 11:21:42 authenticator.go:140: CAKC011E Client certificate not found at '/etc/conjur/ssl/client.pem'
ERROR: 2020/08/13 11:21:42 authenticator.go:184: CAKC015E Login failed
ERROR: 2020/08/13 11:21:42 main.go:85: CSPFK010E Failed to authenticate
```

# Steps to Reproduce
1. Deploy the Secrets Provider or authn-client
2. Check Secrets Provider /authn client logs
3. See failure

<img width="831" alt="Screen Shot 2020-08-13 at 3 07 08 PM" src="https://user-images.githubusercontent.com/19418506/90132568-c50c0480-dd76-11ea-92ae-97f13e47e741.png">

## Expected Results
This initial error log should be appear

## Actual Results (including error logs, if applicable)
A clear and concise description of what actually did happen.

## Reproducible
   * [x] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible
   
## Environment setup
Can you describe the environment in which this product is running? Is it running on a VM / in a container / in a cloud? 
Container locally
Which cloud provider? Which container orchestrator (including version)? 
The more info you can share about your runtime environment, the better we may be able to reproduce the issue.

**Comment by JfcAtCyberArk** [comment]
Hi there,

I got the exact same issue this morning.
/var/log/nginx/access.log from the master says it replied 200 to the inject_client_cert request.
Still, got CAKC011E at the authenticator level. 
First time I run into this.

JFC

**Comment by izgeri** [comment]
@sigalsax is this a duplicate of #119?

**Comment by sigalsax** [comment]
@izgeri yes indeed

**Comment by izgeri** [comment]
@sigalsax can we consolidate the issues then? We can either keep this one or #119.

FYI, fixing this will impact the operation of Secretless too, and will prompt the need for long-time stability tests for another Secretless stable release. I strongly suggest running long-time stability tests for the changes made in this project too, to ensure that the sidecar container continues to operate as expected through token and certificate rotations.

**Comment by sigalsax** [comment]
Solution design by @oburstein-hub here: https://ca-il-confluence.il.cyber-ark.com/display/rndp/K8S+Authenticator+Error+Bug+Solution+Design?src=mail&src.mail.product=confluence-server&src.mail.timestamp=1597665533256&src.mail.notification=com.atlassian.confluence.plugins.share-page%3Ashare-page-notification&src.mail.recipient=ff8080815bd5c281015bfe8881180011

**Comment by sigalsax** [comment]
closing due to duplication
