### ISSUE TITLE
Setup > Setup DAP Server > DAP Prerequisites

### ISSUE THREAD

**Issue by moticless** [cyberark/conjur-authn-k8s-client#151]
### Issue Description
Relevant only to Podman which is **CA**

** Docs > Setup > Setup DAP Server > DAP Prerequisites ** (to delete)
I think we should totally delete this section. It repeats things that being written also in the following dedicated sections to Docker or AWS. 

### Feature Owners

- **Product Manager:**  
- **Product Owner:** @InbalZilberman 
- **R&D Support Engineer:** @oburstein-hub

**Comment by InbalZilberman** [comment]
@moticless can you please specify what in the prerequisits are repeated where? isn't it helpful to see it upfront?

**Comment by izgeri** [comment]
@moticless is this relevant to `conjur-authn-k8s-client` or was this filed in the wrong project?
