### ISSUE TITLE
Add new section: Setup > Setup DAP Server > Podman

### ISSUE THREAD

**Issue by moticless** [cyberark/conjur-authn-k8s-client#152]
We need to add another section to Podman, like the one we have for Docker. Since Podman is CLI compatible with Docker CLI, we can have here a rather thin section which at some point reference to "Setup > Setup DAP Server > Docker", with the requirement from the user to replace each `docker` command with `podman` command.
  
** Setup > Setup DAP Server > Podman ** (Add new section)
[Podman](https://podman.io/) is another engine for maintaining containers. Since Podman CLI is fully compatible with Docker CLI, all the docker-commands of the DAP Server Setup will be also relevant for Podman as well just by replacing `docker` command with `podman` command. 

** Podman requirements for DAP** (New sub-section)
- A DAP Server is packaged as a Docker image. Docker image format is supported by Podman. For high availability, each Master and Standby container should run on a separate VM. Only the Master is supported to run on Podman.
- The user running the DAP container must have root privileges. The DAP container isolates each one of its components (for example, Conjur, NGINX, Postgres, and syslog-ng) by running them as separate processes delegated to dedicated Linux users. These elevated privileges are needed in order to spawn each of these processes using its respective user.
- For DAP Server System requirements, see System Requirements for DAP Server.

** Install Podman ** (New sub-section) 

Podman download and installation instruction available [here](https://podman.io/getting-started/installation.html).

** Load the Conjur image into a registry ** (New sub-section)
Like mentioned above, podman CLI is compatible with docker CLI, and as part of Master installation and configuration steps for Podman, it is assumed from now and on that `alias docker=podman` is configured for the shell that setup DAP Server. 

Follow Docker [Load the Conjur image into a registry](https://docs.cyberark.com/Product-Doc/OnlineHelp/AAM-DAP/Latest/en/Content/Deployment/platforms/docker.html?tocpath=Setup%7CSetup%20DAP%20Server%7CDocker%7C_____0#LoadtheConjurimageintoaregistry) sub-section.

** Install and start a DAP Server **  (New sub-section)
Follow Docker [Install and start a DAP Server ](https://docs.cyberark.com/Product-Doc/OnlineHelp/AAM-DAP/Latest/en/Content/Deployment/platforms/docker.html?tocpath=Setup%7CSetup%20DAP%20Server%7CDocker%7C_____0#LoadtheConjurimageintoaregistry) sub-section.

### Feature Owners

- **Product Manager:**  
- **Product Owner:** @InbalZilberman 
- **R&D Support Engineer:** @oburstein-hub

**Comment by InbalZilberman** [comment]
@moticless can you please place it in confluence ?
I think we should add a section 
Setup > Setup DAP Server > 
* Podman
* Install Podman
* Alias docker to podman
* Load the Conjur image into a registry 
and the rest...

**Comment by izgeri** [comment]
@moticless is this relevant to `conjur-authn-k8s-client`, or was this put in the wrong project?

**Comment by shulifink** [comment]
@moticless - why closed?

**Comment by oburstein-hub** [comment]
Hi @moticless 
Is this document of installation instructions ? If yes - maybe we should coordinate with Shuli to place it in conjur site ?
