### ISSUE TITLE
There is a helm test for the namespace prep helm chart

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-authn-k8s-client#237]
## User story
**As a** Kubernetes admin
**I want** a helm test that I can run after running the cluster prep helm chart
**So that** I can validate that the resources created by the helm chart are sufficient for apps running in my cluster to use the Kubernetes authenticator

## Implementation/Solution Notes
This should be ported from the Cluster Prep Helm chart test in #228

**Comment by diverdane** [comment]
Closing this issue, since the work described in this issue was implemented via:
Issue #333 
[PR #355](https://github.com/cyberark/conjur-authn-k8s-client/pull/355)
