### ISSUE TITLE
bugtype

### ISSUE THREAD

**Issue by daphnaab** [cyberark/conjur-authn-k8s-client#258]
**Feature Overview & Customer Need**
**As a**  Conjur user 
**I would like to** install and run my Conjur CLI in my local machine
**In order to** perform the actions I like most in Conjur and operate it

**As a**  Conjur user 
**I would like to** be able to install from my CD pipeline
**In order to** run Conjur CLI in my pipeline and tests if needed

Conjur Python CLI to be on deployed on VMs or local computers of our users.
The platforms the CLI needs to support are:
- RHEL 7 , 8
- Windows 10
- Mac

The deployment of the should be 
1. Manual 
2. Using a single executable file. Recommended - be the same UX for each platform.
3. The name of the CLI when running it should be "python-conjur-cli" or better yet conjur

**Process Logic & Demo flow**
Conjur user goes to release site of the Python CLI and download the CLI file
Conjur user is running the cli for example:

`conjur --help`
The current response is OK.

The Conjur user can see what version of the cli s/he is using by running
`conjur -v or conjur --version`
conjur cli version 6.0.0

see mocks for more details on the response: https://ljfz3b.axshare.com/#id=yokln4&p=conjur_main_help&g=1

**Support**
If any prerequisite is not met while running the cli a proper message should be given to the user.

**Documentation**
Please provide enhance documentation in online help and readme

**Open issue**
Do we need to sign this single executable? find out with PM
h2. DOD
- [x] Implement an easy way to deploy Conjur Python CLI in all 3 platforms
- [x] Implement the command version as described here ^ 
- [x] Implement the command help according to look and feel of Ruby CLI
- [x] Demo the flow described above
- [ ] Automatic integration tests written according to a test plan and passed successfully
- [x] UT written for all classes\functions\major logic flows and passed successfully
- [ ] Security action items were taken
- [x] Supportability was taken into account - troubleshooting section in the readme enhanced and reviewed by TW & PO
- [ ] Fill in the logs and place here a link to the logs files - link to a page with all logs for CLI saved and reviewed. 
- [ ] Logs were reviewed by TW and PO
- [x] Are there new Audits to this feature? If so please document them and provide here a link
- [x] Configurations were reviewed by PO - link if something changed
- [x] Documentation HO to TW and review docs

**Comment by izgeri** [comment]
@daphnaab this is the wrong project (and wrong `component/X` tags?). can I close this?
