### ISSUE TITLE
The sample application Helm chart has a README.md file

### ISSUE THREAD

**Issue by diverdane** [cyberark/conjur-authn-k8s-client#264]
## Is your feature request related to a problem? Please describe.

Issue #238 implements a Helm chart for deploying one or more instances of a sample "Pet Store" application using a Secretless Broker sidecar container or an authn-k8s sidecar container. This issue adds a README.md file for this Helm chart.

## Describe the solution you would like

The README.md file should contain:

1. An general description of the Helm chart's function.
2. An list of steps required to use the Helm chart, e.g.:

- ~Run scripts to create application Docker images.~
- ~Run Helm install using the Kubernetes cluster prep Helm chart (https://github.com/cyberark/conjur-authn-k8s-client/tree/master/helm/kubernetes-cluster-prep)~
- ~Create application Namespace~
- Run Helm install using the Application prep Helm chart (https://github.com/cyberark/conjur-authn-k8s-client/tree/master/helm/application-namespace-prep)
- Run Helm install of the application deployment Helm chart.

3. Examples of using Helm upgrade
4. A table listing all Helm chart values (description, mandatory or not, defaults, etc.)

## DoD
- [ ] README.md contains general description of the chart's function
- [ ] README.md contains list of instructions on how to use the chart
- [ ] README.md contains upgrade examples
- [ ] README.md contains a table of Helm chart configurable values

**Comment by imheresamir** [comment]
Some more details from Kumbi:

> It should provide enough context for a user to run that helm chart independently.
>
> For example, enabling app-summon-sidecar assumes that
> 1) The container image for the application has summon
> 2) The container will at some point, likely at the start, run summon
> 3) When the container runs summon it will use some secrets.yml to specify paths to predefined secrets that the configured identity must have access to
> 
> For (3) if someone were to use automation scripts then they need to know the policy to run to ensure the secrets are defined, that the identity summon uses has permissions on the secrets etc.
