### ISSUE TITLE
Research - how to reuse environment between tests

### ISSUE THREAD

**Issue by hzur** [cyberark/conjur-authn-k8s-client#276]
### Feature Overview & Customer Need
We want to be able for each test to be able to purge his environment for reuse.

### DOD
[] Review the options.
[] Document in the confluence.

**Comment by izgeri** [comment]
@hzur is this the right repo for this issue?

**Comment by hzur** [comment]
@izgeri -you're right, my bad, forgot to change from the default.
do you know how to move it?

**Comment by hzur** [comment]
closing - replaced with[663](https://app.zenhub.com/workspaces/palmtree-5d99d900491c060001c85cba/issues/conjurinc/aam/633)
