### ISSUE TITLE
Provide documentation for using non-default user on non-OpenShift

### ISSUE THREAD

**Issue by diverdane** [cyberark/conjur-authn-k8s-client#282]
## Is your feature request related to a problem? Please describe.

By default, the authenticator client container runs with the built-in
defaults:

- Username: `authenticator`
- User ID:  `777`
- Group ID: `777`

There are situations where customers would like to run their Conjur authenticator-enabled
Pods using a different user than `authenticator`. For non-OpenShift platforms, It is possible
to configure a Pod that contains the authenticator client container with an arbitrary, non-root user.
However, if the Pod is configured incorrectly for this behavior, the authenticator can end up
crashing with permissions errors when it attempts to read its client SSL certificate.

Clear instructions should be provided in the README.md file.

## Describe the solution you would like

Clear instructions are included in the repository's main README.md file showing
how to run a Pod on a non-OpenShift platform that contains the authenticator client
container using an arbitrary, non-root user.

**Comment by izgeri** [comment]
@alexkalish flagging for you to check if we should have a docs ticket for adding this to the published docs too
