### ISSUE TITLE
Use 'conjur' in the name of Helm charts to distinguish them from other Cyberark charts

### ISSUE THREAD

**Issue by diverdane** [cyberark/conjur-authn-k8s-client#306]
## Is your feature request related to a problem? Please describe.

The names of the following Conjur authentication Helm charts:
- helm/kubernetes-cluster-prep
- helm/application-namespace-prep
- helm/app-deploy
should be changed so that they include `conjur`. These Helm charts will be published to the
Cyberark Helm chart repository (https://github.com/cyberark/helm-charts), so they should
contain `conjur` so they can be distinguished from other (non-Conjur-related) CyberArk Helm charts.

## Describe the solution you would like

Helm charts listed above have names that distinguish them as being Conjur-related.

**Comment by izgeri** [comment]
@diverdane part of the DoD should also be updating the dap-wiki flow with the new names, right?

Also, do we intend to publish the demo app helm chart to our official helm chart repo? I'm not sure whether or not we want to do that - cc @alexkalish in case he has feedback
