### ISSUE TITLE
E2E Workflow Scripts: Use `cyberark/demo-app` directly from DockerHub instead of building a custom image

### ISSUE THREAD

**Issue by imheresamir** [cyberark/conjur-authn-k8s-client#318]
## Describe the solution you would like

E2E workflow scripts should not need to build a custom `cyberark/demo-app` PetStore sample app to include the `summon` binaries. See the linked issue below in which `summon` was added to the `demo-app`. This is the tracking issue for removing the custom image building and just using the `cyberark/demo-app` image from DockerHub after it has been updated.

## Additional context

> I think we should rip all this out in favour of having summon in the demo app (see https://github.com/conjurdemos/pet-store-demo/pull/35).

_Originally posted by @doodlesbykumbi in https://github.com/cyberark/conjur-authn-k8s-client/pull/307#discussion_r636018662_

**Comment by jtuttle** [comment]
The demo-app image has not been pushed to DockerHub for a year and a half, we may need to do a tagged release to get a newer version pushed.
