### ISSUE TITLE
E2E Workflow Scripts: Update policy loading to match dap-wiki

### ISSUE THREAD

**Issue by imheresamir** [cyberark/conjur-authn-k8s-client#322]
## Is your feature request related to a problem? Please describe.

[Script 2](https://github.com/cyberark/conjur-authn-k8s-client/blob/master/bin/test-workflow/2_admin_load_conjur_policies.sh) in `bin/test-workflow/` loads several policies which predate the latest guidelines for policy loading (see `dap-wiki` for current guidelines). It mainly uses old logic for policy loading, and requires that hosts be in a specific policy branch and that the hosts are defined in a way that is no longer documented. 

## Describe the solution you would like

Update and split policy loading to match the simpler way in [dap-wiki](https://github.com/cyberark/dap-wiki/tree/master/how-to-guides/kubernetes), and move loading of the individual policies to the appropriate stages in the workflow. This allows a specific persona to load an individual policy rather than loading all policies at once.

**Comment by jtuttle** [comment]
May require some additional time to untangle and understand the current state of the policy.
