### ISSUE TITLE
Validate E2E workflow in CI

### ISSUE THREAD

**Issue by john-odonnell** [cyberark/conjur-authn-k8s-client#340]
## Is your feature request related to a problem? Please describe.

Before adding E2E tests with more environments and authenticators, it would help to
set up either Jenkins or a GitHub action to validate the E2E workflows. Whichever CI
is used could trigger on each PR and daily to ensure additions work in an ambiguous
environment.

## Describe the solution you would like

CI flow to validate the current E2E workflow path, using either
- [ ] GitHub action
- [ ] Jenkinsfile

The CI flow should also be easily extensible to add other elements of the test matrix described in #310.

**Comment by diverdane** [comment]
+1 for implementing this using GitHub actions. For reference, this GitHub action uses Helm V3 and KinD:
    https://github.com/cyberark/conjur-authn-k8s-client/blob/master/.github/workflows/ci.yaml
so it would be a good starting point!
