### ISSUE TITLE
Final Security review for M0 Simple Kubernetes authn client config

### ISSUE THREAD

**Issue by diverdane** [cyberark/conjur-authn-k8s-client#345]
## Is your feature request related to a problem? Please describe.

In order to reach GA status, we need to do a final security review after all development has been completed.

## Describe the solution you would like

Security review has been done, any issues have been addressed, solution is signed off by Security director.

**Comment by jtuttle** [comment]
pending work on this came out of security review meeting, ~1 pt to finish up
