### ISSUE TITLE
Generate K8S manifests from Helm charts

### ISSUE THREAD

**Issue by imheresamir** [cyberark/conjur-authn-k8s-client#351]
Raw Kubernetes manifests should be generated from the `conjur-config-cluster-prep` and `conjur-config-namespace-prep` Helm charts so that personas configuring a Kubernetes cluster can execute the same simplified workflow without needing Helm (instead using plain `kubectl apply` commands).

Ideally these raw manifests would be generated directly from the Helm charts using `helm template`. Consider adding a Github Action to generate these manifests automatically whenever the Helm charts change.

AC:
- [ ] Manifests should be checked into a public GitHub repo that can be referenced in official docs.
- [ ] Manifests should also be bundled into a single archive (e.g. zip) for each Helm release (e.g. GitHub releases could work).

**Comment by alexkalish** [comment]
@imheresamir: I (finally) added a little more detail to the user story epic.  Applicable to this task are the following:

* Manifests should be checked into a public GitHub repo that can be referenced in official docs.
* Manifests should also be bundled into a single archive (e.g. zip) for each Helm release (e.g. GitHub releases could work).

Both of which we previously discussed, so they shouldn't come as a surprise.  Thanks!
