### ISSUE TITLE
(CA) Refactor and UT struct K8sSecretsHandler

### ISSUE THREAD

**Issue by moticless** [cyberark/conjur-authn-k8s-client#46]
- Need to refactor-out the section that actually HTTP access k8s. The logic currently is being held at retrieveK8sSecret().
- Following this refactor we should be able to mock secret retrieval from Kuberenetes and be able to test various inputs for "conjur-map" data entry.

**Comment by orenbm** [comment]
This ticket was opened in this project instead of in `secrets-provider-for-k8s`. It also looks like there's nothing to do in that project regarding this issue. Closing it.
