### ISSUE TITLE
k8s authenticator client injects secrets

### ISSUE THREAD

**Issue by ismarc** [cyberark/conjur-authn-k8s-client#5]
The authenticator client for k8s and OpenShift should inject secrets so that summon is not necessary to be used.  This should work for both the InitContainer and traditional sidecar mechanism.

**Comment by jtuttle** [comment]
Tasks
- authn client modifications (medium / high)
  - read secrets.yml from shared volume
  - use go API to retrieve secrets
  - write secrets to a shared volume (using standard k8s secrets path)
- discuss security implications (low)
- update demo repo to use new functionality (medium)

**Comment by orenbm** [comment]
@izgeri it looks like the secrets-provider answers this need. Can we close this ticket or do we still want to implement something here?

**Comment by izgeri** [comment]
No, I think this can be closed. Thanks for helping to keep our backlogs neat @orenbm!
