### ISSUE TITLE
Client publishes Docker images only when new version is tagged

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-authn-k8s-client#69]
At current, the client will publish new Docker images for every commit that hits master / every daily run of the master pipeline. New images should be pushed to DockerHub and RedHat only when the version tag changes, however.

AC:
- [x] `./bin/publish` is refactored to publish only when the master branch commit matches that of a github tag (the same way that [secretless does](https://github.com/cyberark/secretless-broker/blob/master/bin/publish))

Follow-up issue: #71

**Comment by JakeQuilty** [comment]
https://github.com/cyberark/conjur-authn-k8s-client/pull/72
