### ISSUE TITLE
Client auto-publishes Docker images to RedHat registry

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-authn-k8s-client#71]
Related to #69

We should investigate automatically publishing to RedHat when we push a new image there. At current, we must manually choose to "publish" when a new image is pushed to RedHat. RedHat appears to have an API endpoint for publishing which we may be able to use to accomplish this programmatically.

AC:

- [ ] New images are auto-published on the RedHat Registry when they are pushed

**Comment by izgeri** [comment]
@JakeQuilty I've updated these issues to separate them for you

**Comment by JakeQuilty** [comment]
https://blog.openshift.com/remotely-push-pull-container-images-openshift/

**Comment by JakeQuilty** [comment]
The `auto-publish` setting in RedHat is turned on. Going to have to wait until next build to see if that changes anything and closing this.
