### ISSUE TITLE
Authenticator container writes version to log on startup

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-authn-k8s-client#93]
## Is your feature request related to a problem? Please describe.

Right now to determine authenticator version we rely on the SHA256 hashes available via `docker inspect`, but this is making it difficult to determine the exact image that was used - especially if the image wasn't taken from dockerhub directly.

## Describe the solution you would like
In cyberark/secretless-broker#944 we added our current implementation of printing the Secretless version on startup - adding a similar startup line to the authenticator container would also be nice.

Note: it should not be part of the public packages of the authenticator - adding it there would mean that every tool that is based on those packages would also print the authenticator version, which would be confusing and redundant.

AC:
- [ ] The authenticator container prints the version on startup. For tag builds, the version should print as the semver tag (eg `v1.2.3`). For dev builds, the version should print as the semver tag + the commit hash (eg `v1.2.3-{hash}`)

**Comment by InbalZilberman** [comment]
@izgeri Can you please explain the note about the public packages?

**Comment by izgeri** [comment]
@InbalZilberman the project has a main.go file that invokes the internal / public golang packages to start up and run the authenticator.

Secretless and the k8s secrets provider both import the public golang packages of this project to run the authenticator as part of their workflows.

Looking at the [main.go](https://github.com/cyberark/conjur-authn-k8s-client/blob/master/cmd/authenticator/main.go) for this project now, it probably makes sense to log a startup message and print the version as one of the first steps in main.go. This has the added benefit of avoiding the problem I am concerned with, which is that Secretless will start and log "Starting Secretless vx.y.z" and then log "Starting authenticator va.b.c", which I think would be a little confusing (and as I noted, redundant, since Secretless refers to the authenticator library version it's using in its NOTICES and go.mod).

Hope this makes sense, but please feel free to ask follow-up questions if any of it is not clear.

**Comment by izgeri** [comment]
@orenbm this is not available in a published release yet - right? I don't think we should close it until it's available to end users, since they can't actually benefit from this change yet

**Comment by orenbm** [comment]
Released a version now, thanks!
